/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rewards from "./rewards";
export type { rewards };
import type * as stakeGame from "./stake_game";
export type { stakeGame };
export * as factories from "./factories";
export type { GameRewards } from "./rewards/GameRewards";
export { GameRewards__factory } from "./factories/rewards/GameRewards__factory";
export type { StakeGame } from "./stake_game/StakeGame";
export { StakeGame__factory } from "./factories/stake_game/StakeGame__factory";
